source 'https://github.com/CocoaPods/Specs.git'

target "CocoaLUTTests" do
  pod "CocoaLUT", :path => "../"
end

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Pods-CocoaLUTTests-CocoaLUT"
        config.build_settings['GCC_GENERATE_TEST_COVERAGE_FILES'] = 'YES'
        config.build_settings['GCC_INSTRUMENT_PROGRAM_FLOW_ARCS'] = 'YES'
      end
    end
  end
end
